name = "music-player"
type = "webpack"
account_id = "your-account-id"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2023-01-01"

[site]
bucket = "./public"
entry-point = "workers-site"
